### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by joshghent** [joshghent/NodeChat#10]

**Comment by richardbmx** [comment]
@joshghent  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by joshghent** [comment]
Thank you @richardbmx for the offer, the issue was completed in #14 however. We have other issues open that you are more than welcome to try out!
